# Generated by Django 4.2.11 on 2025-01-10 11:50

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0004_product_base_product_product_dosagearray_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_variation', models.BooleanField(blank=True, default=False, help_text='Отметьте, если это вариация другого товара', null=True, verbose_name='Является вариацией')),
                ('flavor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вкус')),
                ('dosage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дозировка')),
                ('flavorArray', models.URLField(blank=True, null=True)),
                ('dosageArray', models.URLField(blank=True, null=True)),
                ('name_en', models.CharField(max_length=255, verbose_name='Наименование (EN)')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование товара')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание товара')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('sale_price', models.IntegerField(blank=True, null=True, verbose_name='Цена со скидкой')),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('out_of_stock', 'Нет в наличии')], default='in_stock', max_length=20, verbose_name='Статус товара')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хит')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Акция')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество в упаковке')),
                ('vendor_code', models.CharField(max_length=255, verbose_name='Артикул')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('seo_keywords', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Ключевые слова')),
                ('published_product', models.BooleanField(default=False, verbose_name='Модерацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('base_product', models.ForeignKey(blank=True, help_text='Если это вариация, укажите базовый товар', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product1c_variations', to='marketplace.product', verbose_name='Базовый товар')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_1c', to='marketplace.brand', verbose_name='Бренд')),
                ('categories', models.ManyToManyField(blank=True, related_name='products_1c', to='marketplace.category', verbose_name='Категории')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_1c', to='marketplace.form', verbose_name='Форма')),
                ('manufacturer_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_1c', to='marketplace.country', verbose_name='Страна производитель')),
                ('similar_products', models.ManyToManyField(blank=True, help_text='Товары с похожими характеристиками (например, тот же продукт с другим вкусом)', to='integration_1c.product1c', verbose_name='Похожие товары')),
            ],
            options={
                'verbose_name': 'Товар 1с',
                'verbose_name_plural': 'Товары 1с',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('publish', 'Публикация')], max_length=20, verbose_name='Тип синхронизации')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('product_1c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration_1c.product1c', verbose_name='Товар 1С')),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage1C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images_1c', verbose_name='Изображение товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='integration_1c.product1c')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
