# Generated by Django 4.2.11 on 2024-12-23 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0003_product_dosage_product_flavor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(editable=False, max_length=255, verbose_name='Наименование (EN)')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование на русском')),
                ('vendor_code', models.CharField(max_length=255, unique=True, verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('out_of_stock', 'Нет в наличии')], default='out_of_stock', max_length=20, verbose_name='Статус')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать товар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.product', verbose_name='Опубликованный товар')),
            ],
            options={
                'verbose_name': 'Товар из 1С',
                'verbose_name_plural': 'Товары из 1С',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('publish', 'Публикация')], max_length=20, verbose_name='Тип синхронизации')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('product_1c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration_1c.product1c', verbose_name='Товар 1С')),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизации',
                'ordering': ['-created_at'],
            },
        ),
    ]
