# Generated by Django 4.2.11 on 2024-12-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_extra',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Дополнительный адрес'),
        ),
    ]
