# Generated by Django 4.2.11 on 2024-12-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, to='marketplace.product', verbose_name='Похожие товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('coming_soon', 'Нет в наличии')], default='in_stock', max_length=20, verbose_name='Статус товара'),
        ),
    ]
