# Generated by Django 4.2.11 on 2024-12-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_similar_products_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дозировка'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вкус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, help_text='Товары с похожими характеристиками (например, тот же продукт с другим вкусом)', to='marketplace.product', verbose_name='Похожие товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('out_of_stock', 'Нет в наличии')], default='in_stock', max_length=20, verbose_name='Статус товара'),
        ),
    ]
